spring:
  application:
    name: users-ws
  config:
    import: "optional:configserver:http://localhost:8012"
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8020

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false  # ????? ??
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8010/eureka/


gateway:
  ip: 127.0.0.1

token:
  expiration-time: 3600000
  secret: dgjorufhrsnjdu438fkdj38fdmcv7dm3ckvhrsnjjuwelueivhe848fhedldh5ndk

login:
  url:
    path: /users/login